version: '3.8'

services:
  backend:
    build: ./backend
    container_name: cloud_cinema_backend
    restart: always
    volumes:
      - ./sql_app.db:/app/sql_app.db  # Persist SQLite database
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: cloud_cinema_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
